### ISSUE TITLE
CI release job failing

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/conda-base#30]
The [latest CI release job is failing](https://github.com/nextstrain/conda-base/actions/runs/5059967471/jobs/9082466985) with the following error:
```
Traceback (most recent call last):
  File "/home/runner/work/conda-base/conda-base/.dev-env/bin/anaconda", line 6, in <module>
    from binstar_client.scripts.cli import main
  File "/home/runner/work/conda-base/conda-base/.dev-env/lib/python3.11/site-packages/binstar_client/__init__.py", line 26, in <module>
    from .requests_ext import NullAuth
  File "/home/runner/work/conda-base/conda-base/.dev-env/lib/python3.11/site-packages/binstar_client/requests_ext.py", line 11, in <module>
    from urllib3.filepost import choose_boundary, iter_fields
ImportError: cannot import name 'iter_fields' from 'urllib3.filepost' (/home/runner/work/conda-base/conda-base/.dev-env/lib/python3.11/site-packages/urllib3/filepost.py)
```

**Comment by joverlee521** [comment]
Looking into dependencies locally with `conda-tree`:
```
$ conda-tree -p /Users/jlee2346/Repos/nextstrain/conda-base/.dev-env whoneeds urllib3 -t
urllib3==2.0.2
  ├─ requests 2.31.0 [required: >=1.21.1,<3]
  │  ├─ anaconda-project 0.11.1 [required: any]
  │  │  └─ anaconda-client 1.11.2 [required: >=0.9.1]
  │  │     └─ anaconda-project 0.11.1 [required: any]
  │  │        └─ dependent packages of anaconda-project displayed above
  │  ├─ requests-toolbelt 1.0.0 [required: >=2.0.1,<3.0.0]
  │  │  └─ anaconda-client 1.11.2 [required: >=0.9.1]
  │  │     └─ dependent packages of anaconda-client displayed above
  │  ├─ anaconda-client 1.11.2 [required: >=2.20.0]
  │  │  └─ dependent packages of anaconda-client displayed above
  │  ├─ conda-build 3.24.0 [required: any]
  │  │  └─ boa 0.14.0 [required: >=3.24,<3.25]
  │  └─ conda 23.3.1 [required: >=2.20.1,<3]
  │     ├─ conda-build 3.24.0 [required: >=4.13]
  │     │  └─ dependent packages of conda-build displayed above
  │     └─ mamba 1.4.2 [required: >=4.14,<23.4]
  │        └─ boa 0.14.0 [required: >=1.0,<1.5]
  └─ anaconda-client 1.11.2 [required: >=1.26.4]
     └─ dependent packages of anaconda-client displayed above
```

**Comment by tsibley** [comment]
Sounds good to me.
