### ISSUE TITLE
Installation failing 

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/conda-base#65]
Latest [installation test](https://github.com/nextstrain/conda-base/actions/runs/8665943916) failing for all OS versions. 

Error message
```
error    libmamba Could not solve for environment specs
    Encountered problems while solving:
      - package nextstrain-base-20240321T170340Z-h0dc7051_0_locked requires mafft ==7.525 h2413b67_1, but none of the providers can be installed
    
    The environment can't be solved, aborting the operation
```

I can replicate error locally by forcing a new setup of the Conda runtime: 
```
$ nextstrain setup conda --force
Setting up conda…
Removing existing directory /Users/joverlee/.nextstrain/runtimes/conda/micromamba to start fresh…
Requesting Micromamba from https://api.anaconda.org/download/conda-forge/micromamba/1.1.0/osx-64/micromamba-1.1.0-1.tar.bz2…
Downloading and extracting Micromamba to /Users/joverlee/.nextstrain/runtimes/conda/micromamba…
Removing existing directory /Users/joverlee/.nextstrain/runtimes/conda/env to start fresh…
Installing Conda packages into /Users/joverlee/.nextstrain/runtimes/conda/env…
  - nextstrain-base ==20240321T170340Z

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

nextstrain/noarch                                  135.0 B @ 340.0 B/s  0.4s
nextstrain/osx-64                                   28.0kB @  33.8kB/s  0.8s
bioconda/osx-64                                      4.4MB @   3.4MB/s  1.4s
bioconda/noarch                                      5.2MB @   2.5MB/s  1.8s
conda-forge/noarch                                  16.5MB @   6.5MB/s  2.8s
conda-forge/osx-64                                  35.1MB @   7.0MB/s  5.6s
error    libmamba Could not solve for environment specs
    Encountered problems while solving:
      - package nextstrain-base-20240321T170340Z-h0dc7051_0_locked requires mafft ==7.525 h2413b67_1, but none of the providers can be installed
    
    The environment can't be solved, aborting the operation
    
critical libmamba Could not solve for environment specs
Error running ('/Users/joverlee/.nextstrain/runtimes/conda/micromamba/bin/micromamba', '--root-prefix', '/Users/joverlee/.nextstrain/runtimes/conda/micromamba', '--no-rc', '--no-env', '--yes', 'create', 'nextstrain-base ==20240321T170340Z', '--prefix', '/Users/joverlee/.nextstrain/runtimes/conda/env', '--override-channels', '--strict-channel-priority', '--channel', 'nextstrain', '--channel', 'conda-forge', '--channel', 'bioconda', '--no-py-pin', '--allow-uninstall', '--allow-downgrade')
Traceback (most recent call last):
  File "nextstrain.cli.runner.conda", line 389, in micromamba
    subprocess.run(argv, env = env, check = True)
  File "subprocess", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/Users/joverlee/.nextstrain/runtimes/conda/micromamba/bin/micromamba', '--root-prefix', '/Users/joverlee/.nextstrain/runtimes/conda/micromamba', '--no-rc', '--no-env', '--yes', 'create', 'nextstrain-base ==20240321T170340Z', '--prefix', '/Users/joverlee/.nextstrain/runtimes/conda/env', '--override-channels', '--strict-channel-priority', '--channel', 'nextstrain', '--channel', 'conda-forge', '--channel', 'bioconda', '--no-py-pin', '--allow-uninstall', '--allow-downgrade')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "nextstrain.cli.runner.conda", line 275, in setup_prefix
    micromamba("create", install_spec)
  File "nextstrain.cli.runner.conda", line 391, in micromamba
    raise InternalError(f"Error running {argv!r}") from err
nextstrain.cli.errors.InternalError: Error running ('/Users/joverlee/.nextstrain/runtimes/conda/micromamba/bin/micromamba', '--root-prefix', '/Users/joverlee/.nextstrain/runtimes/conda/micromamba', '--no-rc', '--no-env', '--yes', 'create', 'nextstrain-base ==20240321T170340Z', '--prefix', '/Users/joverlee/.nextstrain/runtimes/conda/env', '--override-channels', '--strict-channel-priority', '--channel', 'nextstrain', '--channel', 'conda-forge', '--channel', 'bioconda', '--no-py-pin', '--allow-uninstall', '--allow-downgrade')

Set up failed!

```

**Comment by victorlin** [comment]
Looks like it's having troubles installing `mafft`. The package versions for macOS (`h2413b67_1`) and Linux (`h031d066_1`) are still showing up on https://anaconda.org/bioconda/mafft/files, but somehow they can't get pulled by the solver.

I get a different version when installing on Linux:

```
$ conda install -c bioconda mafft
…
The following NEW packages will be INSTALLED:
  mafft              bioconda/linux-64::mafft-7.505-hec16e2b_0 
```

**Comment by victorlin** [comment]
I manually triggered a [new build](https://github.com/nextstrain/conda-base/actions/runs/8666319017) of the runtime package, hopefully the solver will find and pull an older version.

**Comment by victorlin** [comment]
New build was successful, and manually triggered [installation checks](https://github.com/nextstrain/conda-base/actions/runs/8666482590) were also successful.

The build updated package versions for macOS (`build: "h2413b67_1" => "h10d778d_0"`) and Linux (`build: "h031d066_1" => "h56fdecd_0"`), still on MAFFT version 7.525.
